### ISSUE TITLE
[BUG/CD] Docker Image fails with Prisma Error Message

### ISSUE THREAD

**Issue by Kaktushose** [nplay-team/moderation-bot#8]
```
Node.js v20.13.1
/usr/src/app/node_modules/.prisma/client/default.js:43
    throw new Error('@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.');
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
    at new PrismaClient (/usr/src/app/node_modules/.prisma/client/default.js:43:11)
    at NPLAYModerationBot.initDB (file:///usr/src/app/dist/bot.js:16:30)
    at file:///usr/src/app/dist/bot.js:48:20
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

**Comment by SachsenspieltCoding** [comment]
Ah jo, das muss ich noch mit einbauen. Die Migration File für die DB fehlt ja auch noch, mach ich, sobald ich keine großen Änderungen an der DB Struktur machen muss

**Comment by Kaktushose** [comment]
sobald wir das haben kann ich ne canary version auf der test guild hosten

**Comment by SachsenspieltCoding** [comment]
Kannst du mal schauen, ob der Commit was gebracht hat?

**Comment by Kaktushose** [comment]
Neue Fehlermeldung
```
 => [bot 2/7] WORKDIR /usr/src/app                                                                                                                                                                                 0.2s
 => [bot 3/7] COPY package*.json ./                                                                                                                                                                                0.1s
 => [bot 4/7] RUN npm ci                                                                                                                                                                                           5.8s
 => [bot 5/7] COPY . .                                                                                                                                                                                             0.5s
 => ERROR [bot 6/7] RUN npm run build                                                                                                                                                                              1.6s
------
 > [bot 6/7] RUN npm run build:
0.393 
0.393 > nplay-moderation-bot@1.0.0 build
0.393 > tsc
0.393 
1.572 src/commands/paragraphCommands.ts(1,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.572 src/commands/paragraphCommands.ts(115,17): error TS7006: Parameter 'paragraph' implicitly has an 'any' type.
1.572 src/commands/reportCommands.ts(1,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.572 src/commands/reportCommands.ts(1,21): error TS2305: Module '"@prisma/client"' has no exported member 'ReportAction'.
1.572 src/embed/data/paragraphEmbeds.ts(1,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.572 src/embed/data/reportEmbeds.ts(3,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.573 src/embed/data/reportEmbeds.ts(3,21): error TS2305: Module '"@prisma/client"' has no exported member 'Report'.
1.573 src/embed/data/reportEmbeds.ts(38,12): error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type '{ WARN: string; TIMEOUT: string; KICK: string; TEMP_BAN: string; BAN: string; }'.
1.573 src/permission/permissionHelpers.ts(48,29): error TS7006: Parameter 'acc' implicitly has an 'any' type.
1.573 src/permission/permissionHelpers.ts(48,34): error TS7006: Parameter 'p' implicitly has an 'any' type.
1.573 src/permission/permissionHelpers.ts(151,10): error TS7006: Parameter 'permissions' implicitly has an 'any' type.
1.573 src/permission/permissionHelpers.ts(151,43): error TS7006: Parameter 'p' implicitly has an 'any' type.
1.573 src/permission/permissionHelpers.ts(162,10): error TS7006: Parameter 'permissions' implicitly has an 'any' type.
1.573 src/permission/permissionHelpers.ts(162,43): error TS7006: Parameter 'p' implicitly has an 'any' type.
1.573 src/reports/reportActions.ts(1,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.573 src/reports/reportActions.ts(1,21): error TS2305: Module '"@prisma/client"' has no exported member 'Report'.
1.575 src/reports/reportsHelper.ts(1,10): error TS2305: Module '"@prisma/client"' has no exported member 'Paragraph'.
1.575 src/reports/reportsHelper.ts(1,21): error TS2305: Module '"@prisma/client"' has no exported member 'Report'.
1.575 src/reports/reportsHelper.ts(1,29): error TS2305: Module '"@prisma/client"' has no exported member 'ReportAction'.
1.575 src/reports/reportsHelper.ts(132,58): error TS7006: Parameter 'paragraphs' implicitly has an 'any' type.
1.575 src/reports/reportsHelper.ts(133,19): error TS7006: Parameter 'paragraph' implicitly has an 'any' type.
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
```

**Comment by SachsenspieltCoding** [comment]
Ah, na klar. Das `prisma generate` muss natürlich vor dem `npm run build` ausgeführt werden. Ich behebe mal die Dockerfile

**Comment by SachsenspieltCoding** [comment]
Jetzt aber

**Comment by Kaktushose** [comment]
Prisma macht keine Probleme mehr, dafür aber discordx

```
nplay-moderation-bot       | file:///usr/src/app/node_modules/@discordx/importer/dist/index.mjs:2
nplay-moderation-bot       | import { glob } from "glob";
nplay-moderation-bot       |          ^^^^
nplay-moderation-bot       | SyntaxError: Named export 'glob' not found. The requested module 'glob' is a CommonJS module, which may not support all module.exports as named exports.
nplay-moderation-bot       | CommonJS modules can always be imported via the default export, for example using:
nplay-moderation-bot       | 
nplay-moderation-bot       | import pkg from 'glob';
nplay-moderation-bot       | const { glob } = pkg;
nplay-moderation-bot       | 
nplay-moderation-bot       |     at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
nplay-moderation-bot       |     at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
nplay-moderation-bot       |     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
nplay-moderation-bot       |     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
nplay-moderation-bot       | 
nplay-moderation-bot       | Node.js v20.14.0
```

**Comment by SachsenspieltCoding** [comment]
sap­per­lot,  was ist denn das? Lokal funktioniert es doch :(

**Comment by SachsenspieltCoding** [comment]
Okay, kein Plan. Ich mach jetzt einfach ein Issue bei discordx auf, außer du hast eine Idee?

**Comment by Kaktushose** [comment]
Ich kenn mich mit discordx halt nicht aus, und das problem googlen hast du wahrscheinlich auch schon probiert

**Comment by SachsenspieltCoding** [comment]
Ja, komischerweise passiert das auch nur in dieser Docker Umgebung. Bei mir löppt alles lokal in Docker unter Ubuntu/WSL
